name: Publish Merge

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Code checkout
      uses: actions/checkout@master

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy web files to server with scp
      uses: appleboy/scp-action@master
      with:
          source: frontend/build/
          target: ${{ secrets.REMOTE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}

    - name: Backup, deploy then remove old deployment
      uses: appleboy/ssh-action@master
      with:
          script: |
            mv ${{ secrets.REMOTE_TARGET }}/html ${{ secrets.REMOTE_TARGET }}/html-backup
            mv ${{ secrets.REMOTE_TARGET }}/build ${{ secrets.REMOTE_TARGET }}/html
            rm -rf ${{ secrets.REMOTE_TARGET }}/html-backup
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
